class AppLocalizations {
  final String currentLanguage;

  AppLocalizations(this.currentLanguage);

  String get(String key) {
    switch (currentLanguage) {
      case 'Türkçe':
        return _turkishTranslations[key] ?? key;
      case 'English':
        return _englishTranslations[key] ?? key;
      case 'Deutsch':
        return _germanTranslations[key] ?? key;
      case 'Français':
        return _frenchTranslations[key] ?? key;
      case 'Español':
        return _spanishTranslations[key] ?? key;
      default:
        return _turkishTranslations[key] ?? key;
    }
  }

  final Map<String, String> _turkishTranslations = {
    'ayarlar': 'Ayarlar',
    'bildirimler': 'Bildirimler',
    'bildirimler_aciklama': 'Sistem bildirimlerini al',
    'karanlik_mod': 'Karanlık Mod',
    'karanlik_mod_aciklama': 'Karanlık tema kullan',
    'otomatik_kapi': 'Otomatik Kapı',
    'otomatik_kapi_aciklama': 'Güneşe göre kapıyı otomatik aç/kapat',
    'dil': 'Dil',
    'dil_aciklama': 'Uygulama dilini değiştir',
    'ayarlari_kaydet': 'Ayarları Kaydet',
    'ayarlar_kaydedildi': 'Ayarlar kaydedildi',
    'sicaklik': 'Sıcaklık',
    'sicaklik_kontrol': 'Sıcaklık Kontrolü',
    'mevcut_sicaklik': 'Mevcut Sıcaklık',
    'yem_su': 'Yem & Su',
    'yem_su_kontrol': 'Yem ve Su Kontrolü',
    'yem_seviyesi': 'Yem Seviyesi',
    'su_seviyesi': 'Su Seviyesi',
    'kayan_kapi': 'Kayan Kapı',
    'kapi_kontrol': 'Kapı Kontrolü',
    'kapi_durumu': 'Kapı Durumu',
    'acik': 'Açık',
    'kapali': 'Kapalı',
    'tavuk_sayisi': 'Tavuk Sayısı',
    'tavuk_kontrol': 'Tavuk Sayısı Kontrolü',
    'mevcut_tavuk': 'Mevcut Tavuk Sayısı',
    'artir': 'Artır',
    'azalt': 'Azalt',
    'kaydet': 'Kaydet',
    'kaydedildi': 'Kaydedildi',
    'kontrol_paneli': 'Kontrol Paneli',
    'canli_destek': 'Canlı Destek',
    'canli_destek_aciklama': 'WhatsApp üzerinden destek alın',
    'whatsapp_hata': 'WhatsApp açılamadı',
    'kamera_kontrol': 'Kamera Kontrol',
    'canli_yayin': 'Canlı Yayın',
    'dis_kamera': 'Dış Kamera',
    'mevcut_hayvan_sayisi': 'Mevcut Hayvan Sayısı',
    'son_yabanci_hayvan': 'Son Yabancı Hayvan Tespiti',
    'hareket_algilama': 'Hareket Algılama',
    'gece_gorus': 'Gece Görüşü',
    'alarm_gecmisi': 'Alarm Geçmişi',
    'gecmisi_temizle': 'Geçmişi Temizle',
    'istatistikler': 'İstatistikler',
    'gunluk_hareketler': 'Günlük Hayvan Hareketleri',
    'haftalik_hayvan_sayisi': 'Haftalık Hayvan Sayısı',
    'hava_durumu': 'Hava Durumu',
    'sicaklik_nem': 'Sıcaklık ve Nem',
    'isik_seviyesi': 'Işık Seviyesi',
  };

  final Map<String, String> _englishTranslations = {
    'ayarlar': 'Settings',
    'bildirimler': 'Notifications',
    'bildirimler_aciklama': 'Receive system notifications',
    'karanlik_mod': 'Dark Mode',
    'karanlik_mod_aciklama': 'Use dark theme',
    'otomatik_kapi': 'Automatic Door',
    'otomatik_kapi_aciklama': 'Automatically open/close door based on sunlight',
    'dil': 'Language',
    'dil_aciklama': 'Change application language',
    'ayarlari_kaydet': 'Save Settings',
    'ayarlar_kaydedildi': 'Settings saved',
    'sicaklik': 'Temperature',
    'sicaklik_kontrol': 'Temperature Control',
    'mevcut_sicaklik': 'Current Temperature',
    'yem_su': 'Feed & Water',
    'yem_su_kontrol': 'Feed and Water Control',
    'yem_seviyesi': 'Feed Level',
    'su_seviyesi': 'Water Level',
    'kayan_kapi': 'Sliding Door',
    'kapi_kontrol': 'Door Control',
    'kapi_durumu': 'Door Status',
    'acik': 'Open',
    'kapali': 'Closed',
    'tavuk_sayisi': 'Chicken Count',
    'tavuk_kontrol': 'Chicken Count Control',
    'mevcut_tavuk': 'Current Chicken Count',
    'artir': 'Increase',
    'azalt': 'Decrease',
    'kaydet': 'Save',
    'kaydedildi': 'Saved',
    'kontrol_paneli': 'Control Panel',
    'canli_destek': 'Live Support',
    'canli_destek_aciklama': 'Get support via WhatsApp',
    'whatsapp_hata': 'Couldn\'t open WhatsApp',
    'kamera_kontrol': 'Camera Control',
    'canli_yayin': 'Live Stream',
    'dis_kamera': 'External Camera',
    'mevcut_hayvan_sayisi': 'Current Animal Count',
    'son_yabanci_hayvan': 'Last Unknown Animal Detection',
    'hareket_algilama': 'Motion Detection',
    'gece_gorus': 'Night Vision',
    'alarm_gecmisi': 'Alarm History',
    'gecmisi_temizle': 'Clear History',
    'istatistikler': 'Statistics',
    'gunluk_hareketler': 'Daily Animal Movements',
    'haftalik_hayvan_sayisi': 'Weekly Animal Count',
    'hava_durumu': 'Weather',
    'sicaklik_nem': 'Temperature & Humidity',
    'isik_seviyesi': 'Light Level',
  };

  final Map<String, String> _germanTranslations = {
    'ayarlar': 'Einstellungen',
    'bildirimler': 'Benachrichtigungen',
    'bildirimler_aciklama': 'Systembenachrichtigungen empfangen',
    'karanlik_mod': 'Dunkelmodus',
    'karanlik_mod_aciklama': 'Dunkles Theme verwenden',
    'otomatik_kapi': 'Automatische Tür',
    'otomatik_kapi_aciklama':
        'Tür automatisch öffnen/schließen basierend auf Sonnenlicht',
    'dil': 'Sprache',
    'dil_aciklama': 'Anwendungssprache ändern',
    'ayarlari_kaydet': 'Einstellungen speichern',
    'ayarlar_kaydedildi': 'Einstellungen gespeichert',
    'sicaklik': 'Temperatur',
    'sicaklik_kontrol': 'Temperaturkontrolle',
    'mevcut_sicaklik': 'Aktuelle Temperatur',
    'yem_su': 'Futter & Wasser',
    'yem_su_kontrol': 'Futter- und Wasserkontrolle',
    'yem_seviyesi': 'Futterniveau',
    'su_seviyesi': 'Wasserniveau',
    'kayan_kapi': 'Schiebetür',
    'kapi_kontrol': 'Türsteuerung',
    'kapi_durumu': 'Türstatus',
    'acik': 'Offen',
    'kapali': 'Geschlossen',
    'tavuk_sayisi': 'Hühneranzahl',
    'tavuk_kontrol': 'Hühneranzahl-Kontrolle',
    'mevcut_tavuk': 'Aktuelle Hühneranzahl',
    'artir': 'Erhöhen',
    'azalt': 'Verringern',
    'kaydet': 'Speichern',
    'kaydedildi': 'Gespeichert',
    'kontrol_paneli': 'Kontrolltafel',
    'canli_destek': 'Live-Support',
    'canli_destek_aciklama': 'Support über WhatsApp erhalten',
    'whatsapp_hata': 'WhatsApp konnte nicht geöffnet werden',
    'kamera_kontrol': 'Kamerasteuerung',
    'canli_yayin': 'Live-Stream',
    'dis_kamera': 'Außenkamera',
    'mevcut_hayvan_sayisi': 'Aktuelle Tierzahl',
    'son_yabanci_hayvan': 'Letzte unbekannte Tiererkennung',
    'hareket_algilama': 'Bewegungserkennung',
    'gece_gorus': 'Nachtsicht',
    'alarm_gecmisi': 'Alarmverlauf',
    'gecmisi_temizle': 'Verlauf löschen',
    'istatistikler': 'Statistiken',
    'gunluk_hareketler': 'Tägliche Tierbewegungen',
    'haftalik_hayvan_sayisi': 'Wöchentliche Tierzahl',
    'hava_durumu': 'Wetter',
    'sicaklik_nem': 'Temperatur & Luftfeuchtigkeit',
    'isik_seviyesi': 'Lichtstärke',
  };

  final Map<String, String> _frenchTranslations = {
    'ayarlar': 'Paramètres',
    'bildirimler': 'Notifications',
    'bildirimler_aciklama': 'Recevoir les notifications système',
    'karanlik_mod': 'Mode Sombre',
    'karanlik_mod_aciklama': 'Utiliser le thème sombre',
    'otomatik_kapi': 'Porte Automatique',
    'otomatik_kapi_aciklama':
        'Ouvrir/fermer automatiquement la porte selon la lumière du soleil',
    'dil': 'Langue',
    'dil_aciklama': 'Changer la langue de l\'application',
    'ayarlari_kaydet': 'Enregistrer les paramètres',
    'ayarlar_kaydedildi': 'Paramètres enregistrés',
    'sicaklik': 'Température',
    'sicaklik_kontrol': 'Contrôle de la température',
    'mevcut_sicaklik': 'Température actuelle',
    'yem_su': 'Nourriture & Eau',
    'yem_su_kontrol': 'Contrôle de la nourriture et de l\'eau',
    'yem_seviyesi': 'Niveau de nourriture',
    'su_seviyesi': 'Niveau d\'eau',
    'kayan_kapi': 'Porte Coulissante',
    'kapi_kontrol': 'Contrôle de la porte',
    'kapi_durumu': 'État de la porte',
    'acik': 'Ouvert',
    'kapali': 'Fermé',
    'tavuk_sayisi': 'Nombre de Poules',
    'tavuk_kontrol': 'Contrôle du nombre de poules',
    'mevcut_tavuk': 'Nombre actuel de poules',
    'artir': 'Augmenter',
    'azalt': 'Diminuer',
    'kaydet': 'Enregistrer',
    'kaydedildi': 'Enregistré',
    'kontrol_paneli': 'Panneau de Contrôle',
    'canli_destek': 'Support en Direct',
    'canli_destek_aciklama': 'Obtenir de l\'aide via WhatsApp',
    'whatsapp_hata': 'Impossible d\'ouvrir WhatsApp',
    'kamera_kontrol': 'Contrôle de la Caméra',
    'canli_yayin': 'Diffusion en Direct',
    'dis_kamera': 'Caméra Externe',
    'mevcut_hayvan_sayisi': 'Nombre Actuel d\'Animaux',
    'son_yabanci_hayvan': 'Dernière Détection d\'Animal Inconnu',
    'hareket_algilama': 'Détection de Mouvement',
    'gece_gorus': 'Vision Nocturne',
    'alarm_gecmisi': 'Historique des Alarmes',
    'gecmisi_temizle': 'Effacer l\'Historique',
    'istatistikler': 'Statistiques',
    'gunluk_hareketler': 'Mouvements Quotidiens des Animaux',
    'haftalik_hayvan_sayisi': 'Nombre Hebdomadaire d\'Animaux',
    'hava_durumu': 'Météo',
    'sicaklik_nem': 'Température & Humidité',
    'isik_seviyesi': 'Niveau de Lumière',
  };

  final Map<String, String> _spanishTranslations = {
    'ayarlar': 'Ajustes',
    'bildirimler': 'Notificaciones',
    'bildirimler_aciklama': 'Recibir notificaciones del sistema',
    'karanlik_mod': 'Modo Oscuro',
    'karanlik_mod_aciklama': 'Usar tema oscuro',
    'otomatik_kapi': 'Puerta Automática',
    'otomatik_kapi_aciklama':
        'Abrir/cerrar puerta automáticamente según la luz solar',
    'dil': 'Idioma',
    'dil_aciklama': 'Cambiar el idioma de la aplicación',
    'ayarlari_kaydet': 'Guardar Ajustes',
    'ayarlar_kaydedildi': 'Ajustes guardados',
    'sicaklik': 'Temperatura',
    'sicaklik_kontrol': 'Control de Temperatura',
    'mevcut_sicaklik': 'Temperatura Actual',
    'yem_su': 'Alimento & Agua',
    'yem_su_kontrol': 'Control de Alimento y Agua',
    'yem_seviyesi': 'Nivel de Alimento',
    'su_seviyesi': 'Nivel de Agua',
    'kayan_kapi': 'Puerta Deslizante',
    'kapi_kontrol': 'Control de Puerta',
    'kapi_durumu': 'Estado de la Puerta',
    'acik': 'Abierto',
    'kapali': 'Cerrado',
    'tavuk_sayisi': 'Cantidad de Pollos',
    'tavuk_kontrol': 'Control de Cantidad de Pollos',
    'mevcut_tavuk': 'Cantidad Actual de Pollos',
    'artir': 'Aumentar',
    'azalt': 'Disminuir',
    'kaydet': 'Guardar',
    'kaydedildi': 'Guardado',
    'kontrol_paneli': 'Panel de Control',
    'canli_destek': 'Soporte en Vivo',
    'canli_destek_aciklama': 'Obtener ayuda a través de WhatsApp',
    'whatsapp_hata': 'No se pudo abrir WhatsApp',
    'kamera_kontrol': 'Control de Cámara',
    'canli_yayin': 'Transmisión en Vivo',
    'dis_kamera': 'Cámara Externa',
    'mevcut_hayvan_sayisi': 'Cantidad Actual de Animales',
    'son_yabanci_hayvan': 'Última Detección de Animal Desconocido',
    'hareket_algilama': 'Detección de Movimiento',
    'gece_gorus': 'Visión Nocturna',
    'alarm_gecmisi': 'Historial de Alarmas',
    'gecmisi_temizle': 'Limpiar Historial',
    'istatistikler': 'Estadísticas',
    'gunluk_hareketler': 'Movimientos Diarios de Animales',
    'haftalik_hayvan_sayisi': 'Cantidad Semanal de Animales',
    'hava_durumu': 'Clima',
    'sicaklik_nem': 'Temperatura & Humedad',
    'isik_seviyesi': 'Nivel de Luz',
  };
}
